/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as StakeRouteImport } from './routes/stake'
import { Route as YieldRouteImport } from './routes/yield'
import { Route as PoolChainIdAddressRouteImport } from './routes/pool.$chainId.$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeRoute = StakeRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => rootRouteImport,
} as any)
const YieldRoute = YieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolChainIdAddressRoute = PoolChainIdAddressRouteImport.update({
  id: '/pool/$chainId/$address',
  path: '/pool/$chainId/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/faqs': typeof FaqsRoute
  '/history': typeof HistoryRoute
  '/pools': typeof PoolsRoute
  '/preview': typeof PreviewRoute
  '/referral': typeof ReferralRoute
  '/roadmap': typeof RoadmapRoute
  '/stake': typeof StakeRoute
  '/yield': typeof YieldRoute
  '/pool/$chainId/$address': typeof PoolChainIdAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/faqs': typeof FaqsRoute
  '/history': typeof HistoryRoute
  '/pools': typeof PoolsRoute
  '/preview': typeof PreviewRoute
  '/referral': typeof ReferralRoute
  '/roadmap': typeof RoadmapRoute
  '/stake': typeof StakeRoute
  '/yield': typeof YieldRoute
  '/pool/$chainId/$address': typeof PoolChainIdAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/faqs': typeof FaqsRoute
  '/history': typeof HistoryRoute
  '/pools': typeof PoolsRoute
  '/preview': typeof PreviewRoute
  '/referral': typeof ReferralRoute
  '/roadmap': typeof RoadmapRoute
  '/stake': typeof StakeRoute
  '/yield': typeof YieldRoute
  '/pool/$chainId/$address': typeof PoolChainIdAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/dashboard'
    | '/docs'
    | '/faqs'
    | '/history'
    | '/pools'
    | '/preview'
    | '/referral'
    | '/roadmap'
    | '/stake'
    | '/yield'
    | '/pool/$chainId/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/dashboard'
    | '/docs'
    | '/faqs'
    | '/history'
    | '/pools'
    | '/preview'
    | '/referral'
    | '/roadmap'
    | '/stake'
    | '/yield'
    | '/pool/$chainId/$address'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/dashboard'
    | '/docs'
    | '/faqs'
    | '/history'
    | '/pools'
    | '/preview'
    | '/referral'
    | '/roadmap'
    | '/stake'
    | '/yield'
    | '/pool/$chainId/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  FaqsRoute: typeof FaqsRoute
  HistoryRoute: typeof HistoryRoute
  PoolsRoute: typeof PoolsRoute
  PreviewRoute: typeof PreviewRoute
  ReferralRoute: typeof ReferralRoute
  RoadmapRoute: typeof RoadmapRoute
  StakeRoute: typeof StakeRoute
  YieldRoute: typeof YieldRoute
  PoolChainIdAddressRoute: typeof PoolChainIdAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stake': {
      id: '/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof StakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yield': {
      id: '/yield'
      path: '/yield'
      fullPath: '/yield'
      preLoaderRoute: typeof YieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/$chainId/$address': {
      id: '/pool/$chainId/$address'
      path: '/pool/$chainId/$address'
      fullPath: '/pool/$chainId/$address'
      preLoaderRoute: typeof PoolChainIdAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  FaqsRoute: FaqsRoute,
  HistoryRoute: HistoryRoute,
  PoolsRoute: PoolsRoute,
  PreviewRoute: PreviewRoute,
  ReferralRoute: ReferralRoute,
  RoadmapRoute: RoadmapRoute,
  StakeRoute: StakeRoute,
  YieldRoute: YieldRoute,
  PoolChainIdAddressRoute: PoolChainIdAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
